---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


- name: Create a directory /var/lib/pgdocker
  file:
    path: "{{ postgres_data_dir }}" # /var/lib/pgdocker
    state: directory
    mode: '0755'

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"

- name: Clone AWX into {{ awx_repo_dir }}
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: yes
    accept_hostkey: yes

#
